---
title: "CodeBook"
author: "Amy Shelton"
date: "2023-07-31"
output: html_document
---

The first step was to download the project zip file. I downloaded the zip file into a folder named Project. I created an RProject named Project.Rproj, a readme markdown file named README.Rmd and a code book markdown file named CodeBook.Rmd. I am using RStudio 2023.06.0+421, and R version 4.3.0.

The first step is to unzip the zip file.

This created a folder named UCI HAR Dataset, with subfolders for the **test** and **train** data. This folder also contains 4 text files describing the data, activity_labels.txt, features-info.txt, features.txt and README.txt. In the test folder we will use X_test.txt, y_test.txt and subject_test.txt files. In the train folder we will use the X_train.txt, y_train.txt and subject_train.txt files.

Six activities were measured by the accelerometer and gyroscope:
  
1. Walking
2. Walking upstairs
3. Walking downstairs
4. Sitting
5. Standing
6. laying

The measurements are in the X_test and X_train files. Their activity (1-6) is in the y-test and y_train files. The subjects are listed in the subject_test and subject_train files. The activity levels (1-6) and names (Walking, etc.) are stored in the activity_labels file. Finally, the features file contains the label of what was measured in each column.

Transformations are described in the script below, step-by-step. 

load dplyr

**library(dplyr)**


##### **_Step 1_**
Merge the training and test data set to create one data set for all 30 subjects

My working directory is .../UCI HAR Dataset
Read the test data files into R
The X-test file contains the test measurement summaries
The y-test file contains the activity performed for the test measurement
The subject_test file identities the subject number 1-21

**test_values = read.table(file.path("test", "X_test.txt"))**
**test_activity = read.table(file.path("test", "y_test.txt"))**
**test_subject = read.table(file.path("test", "subject_test.txt"))**


Read the train data files into R, same contents as test subjects, 
x- measurements, y- activity performed 1-6, subject- identifies which subject it was 22-30

**train_values = read.table(file.path("train", "X_train.txt"))**
**train_activity = read.table(file.path("train", "y_train.txt"))**
**train_subject = read.table(file.path("train", "subject_train.txt"))**


Read the features file into R, features identifies what the columns are, column names

**features = read.table("features.txt", as.is = TRUE)**

Read the activity labels into R and add column names

**labels = read.table("activity_labels.txt")**
**colnames(labels) <- c("activityid","activity")**

Create a single data file from the 8 files

**test <- cbind(test_subject, test_activity, test_values)**
**train <- cbind(train_subject, train_activity, train_values)**

Combine test and train subject data

**activity <- rbind(train , test)**

Name the columns in the combined file

**colnames(activity) <- c("subject", "activity", features[, 2])**

##### **_Step 2_** 
Extract only the measurements on the mean and standard deviation for each measurement

Create the new file with the average and standard deviation measurements
Use grep1 on the column names to find the mean and standard deviation columns

**msd_dataset <- grepl("subject|activity|mean|std", colnames(activity))**

Keep data in these columns only, save to a new file

**Activity <- activity[, msd_dataset]**


####Step 3
Use descriptive activity names to name the activities in the data set

Replace activity values 1-6 with named factor labels

**Activity$activity <- factor(Activity$activity,levels = labels[, 1], labels = labels[, 2])**


####Step 4
Appropriately label the data set with descriptive variable names

Get column names

**ActivityCols <- colnames(Activity)**

Remove special characters, the - and () and replace it with nothing

**ActivityCols <- gsub("[\\(\\)-]", "", ActivityCols)**

Make the names more readable (descriptive)

**ActivityCols <- gsub("^f", "frequencyDomain", ActivityCols)**
**ActivityCols <- gsub("^t", "time", ActivityCols)**
**ActivityCols <- gsub("Acc", "Accelerometer", ActivityCols)**
**ActivityCols <- gsub("Gyro", "Gyroscope", ActivityCols)**
**ActivityCols <- gsub("Mag", "Magnitude", ActivityCols)**
**ActivityCols <- gsub("Freq", "Frequency", ActivityCols)**
**ActivityCols <- gsub("mean", "Mean", ActivityCols)**
**ActivityCols <- gsub("std", "StandardDeviation", ActivityCols)**

Fix an error

**ActivityCols <- gsub("BodyBody", "Body", ActivityCols)**

Use new labels as column names

**colnames(Activity) <- ActivityCols**


#### Step 5
Create a second independent tidy data set with the average
of each variable for each activity and each subject, using #4's dataset

Group by subject and activity and summarise using mean

**ActivityMeans <- Activity %>% **
  **group_by(subject, activity) %/%**
  **summarise(funs(mean))**

Output to file "tidy_data.txt"

**write.table(ActivityMeans, "tidy_data.txt", row.names = FALSE, quote = FALSE)**
